"""Add DataLayer v1

Revision ID: 8136796b2a97
Revises: 4e639e3c58a5
Create Date: 2024-04-03 05:02:49.713215

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "8136796b2a97"
down_revision: Union[str, None] = "4e639e3c58a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
