"""added self reference

Revision ID: e8826025cfba
Revises: de5c45ed2007
Create Date: 2024-01-28 19:26:46.719142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8826025cfba'
down_revision: Union[str, None] = 'de5c45ed2007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('parent_topic_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'topics', 'topics', ['parent_topic_id'], ['topic_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topics', type_='foreignkey')
    op.drop_column('topics', 'parent_topic_id')
    # ### end Alembic commands ###
