from app.models.answersheet_models import *
from app.models.question_models import *
from app.models.quiz_models import *
from app.models.topic_models import *
from app.models.user_model import *
from app.models.university_model import *
from app.models.link_models import *
from app.models.health_model import *
from app.models.base import *
